import type { Step } from "./App";
import "./Panel.css";

export function Panel({ step, setStep }: { step: Step; setStep: (step: Step) => void }) {
  return (
    <div className="panel">
      <h2>Citibike accessibility</h2>
      {step === 0 && (
        <>
          <p>
            Use this tool to see how far you can get with <strong>$3</strong> on an Citibike E-bike
            with a membership.
          </p>
          <p>To get started, find your local station and click on it.</p>
        </>
      )}
      {step === 1 && (
        <>
          <p>
            This is the current area you can ride to with <strong>$3</strong> — about 11 minutes at
            $0.27 per minute.
          </p>
          <p>
            Next, click the button below to see how far you could get for the same price if we
            capped the fares.
          </p>
          <button className="button-primary" onClick={() => setStep(2)}>
            Cap Citibike fares
          </button>
        </>
      )}
      {step === 2 && (
        <>
          <p>
            This is how far you could ride if we <strong>capped Citibike fares at $3</strong> for
            all rides under 45 minutes.
          </p>
          <button className="button" onClick={() => setStep(0)}>
            Try another station
          </button>
        </>
      )}
      {step === 3 && (
        <>
          <p>Here you can play around with the settings.</p>
          <p>
            The shapes generated by this tool are called <strong>isochrones</strong> and are
            commonly used to visualize{" "}
            <strong>
              <i>access</i>
            </strong>{" "}
            — how many places a person can reach by some mode of transportation.
          </p>
        </>
      )}
    </div>
  );
}
