services:
  valhalla:
    init: true
    restart: always
    build:
      context: .
    volumes:
      - ./valhalla/tiles.tar:/data/valhalla/tiles.tar
    environment:
      TILE_PATH: /data/valhalla/tiles.tar
    ports:
      - "8002:8002"
